# Generated by Django 4.1 on 2024-08-11 19:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='Player',
        ),
        migrations.RenameModel(
            old_name='TeamApplication',
            new_name='RequestToTeam',
        ),
        migrations.RenameField(
            model_name='requesttoteam',
            old_name='participant',
            new_name='player',
        ),
        migrations.RenameModel(
            old_name='Creator',
            new_name='TeamLead',
        ),
        migrations.CreateModel(
            name='ShareBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('create_dt', models.DateTimeField(default=datetime.datetime.now)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='teams.teamlead')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='teams.teamlead')),
            ],
        ),
    ]
