# Generated by Django 4.1 on 2024-08-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_rename_participant_player_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игрок'},
        ),
        migrations.AlterModelOptions(
            name='requesttoteam',
            options={'verbose_name': 'Заявка в команду', 'verbose_name_plural': 'Заявка в команду'},
        ),
        migrations.AlterModelOptions(
            name='sharebonus',
            options={'verbose_name': 'Поделиться баллами', 'verbose_name_plural': 'Поделиться баллами'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команда'},
        ),
        migrations.AlterModelOptions(
            name='teamlead',
            options={'verbose_name': 'Тимлид', 'verbose_name_plural': 'Тимлид'},
        ),
    ]
