# Generated by Django 4.1 on 2024-08-22 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0004_alter_team_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlead',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
