# Generated by Django 4.1 on 2024-08-23 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_team_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='max_members',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team'),
        ),
    ]
