# Generated by Django 4.1 on 2024-08-23 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0008_team_max_members_alter_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttoteam',
            name='status_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
