# Generated by Django 4.1 on 2024-08-24 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_requesttoteam_status_id_alter_team_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttoteam',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='teams.player'),
        ),
    ]
