# Generated by Django 4.1 on 2024-08-24 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_alter_requesttoteam_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='user',
        ),
    ]
