# Generated by Django 4.1 on 2024-08-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_rename_name_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
