# Generated by Django 4.1 on 2024-08-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_remove_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttoteam',
            name='status_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
